version: '3.9'

services:
  ai-recruiter-agent:
    build: .
    ports:
      - "8000:8000"
    # volumes:
    #   - ./src/images:/usr/src/app/src/images
    environment:
      - NODE_ENV=production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s